name: Build Pull Request

on:
  pull_request

jobs:
  build-pr:
    name: Build Pull Request
    uses: juitnow/workflows-public/.github/workflows/build.yml@main
    secrets:
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
